### ISSUE TITLE
Angular vendor modules in src/app/app.module.js should be generated from assets.yml

### ISSUE THREAD

**Issue by lukaszgrolik** [lukaszgrolik/generator-lukaszgrolik-angular#2]
Vendor scripts in assets.yml need some additional property to define angular module, e.g.

``` yml
vendorScripts:
  - src: bower_components/angular-ui-router/release/angular-ui-router.js
    dist: bower_components/angular-ui-router/release/angular-ui-router.min.js
    ngModule: ui.router
```
